[project]
name = "halberd"
version = "3.0.0"
description = "Multi-cloud agentic attack tool for security teams"
authors = [{ name = "Vectra AI Research", email = "research@vectra.ai" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"

dependencies = [
    "adal==1.2.7",
    "aiohttp==3.11.11",
    "aiosignal==1.3.1",
    "ansi2html==1.8.0",
    "anyio==4.2.0",
    "async-timeout==4.0.3",
    "attrs==23.2.0",
    "azure-common==1.1.28",
    "azure-core==1.29.7",
    "azure-identity==1.16.0",
    "azure-keyvault-keys==4.9.0",
    "azure-keyvault-secrets==4.8.0",
    "azure-mgmt-advisor==1.0.1",
    "azure-mgmt-applicationinsights==0.1.1",
    "azure-mgmt-authorization==4.0.0",
    "azure-mgmt-automation==1.0.0",
    "azure-mgmt-batch==5.0.1",
    "azure-mgmt-batchai==2.0.0",
    "azure-mgmt-billing==0.2.0",
    "azure-mgmt-cdn==3.1.0",
    "azure-mgmt-cognitiveservices==3.0.0",
    "azure-mgmt-commerce==1.0.1",
    "azure-mgmt-compute==31.0.0",
    "azure-mgmt-consumption==2.0.0",
    "azure-mgmt-containerinstance==1.5.0",
    "azure-mgmt-containerregistry==2.8.0",
    "azure-mgmt-containerservice==4.4.0",
    "azure-mgmt-core==1.4.0",
    "azure-mgmt-cosmosdb==0.4.1",
    "azure-mgmt-datafactory==0.6.0",
    "azure-mgmt-datalake-analytics==0.6.0",
    "azure-mgmt-datalake-nspkg==3.0.1",
    "azure-mgmt-datalake-store==0.5.0",
    "azure-mgmt-datamigration==1.0.0",
    "azure-mgmt-devspaces==0.1.0",
    "azure-mgmt-devtestlabs==2.2.0",
    "azure-mgmt-dns==2.1.0",
    "azure-mgmt-eventgrid==1.0.0",
    "azure-mgmt-eventhub==2.6.0",
    "azure-mgmt-hanaonazure==0.1.1",
    "azure-mgmt-iotcentral==0.1.0",
    "azure-mgmt-iothub==0.5.0",
    "azure-mgmt-iothubprovisioningservices==0.2.0",
    "azure-mgmt-keyvault==10.3.0",
    "azure-mgmt-loganalytics==0.2.0",
    "azure-mgmt-logic==10.0.0",
    "azure-mgmt-machinelearningcompute==0.4.1",
    "azure-mgmt-managementgroups==0.1.0",
    "azure-mgmt-managementpartner==0.1.1",
    "azure-mgmt-maps==0.1.0",
    "azure-mgmt-marketplaceordering==0.1.0",
    "azure-mgmt-media==1.0.1",
    "azure-mgmt-monitor==6.0.2",
    "azure-mgmt-msi==0.2.0",
    "azure-mgmt-network==2.7.0",
    "azure-mgmt-notificationhubs==2.1.0",
    "azure-mgmt-nspkg==3.0.2",
    "azure-mgmt-policyinsights==0.1.0",
    "azure-mgmt-powerbiembedded==2.0.0",
    "azure-mgmt-rdbms==1.9.0",
    "azure-mgmt-recoveryservices==0.3.0",
    "azure-mgmt-recoveryservicesbackup==0.3.0",
    "azure-mgmt-redis==5.0.0",
    "azure-mgmt-relay==0.1.0",
    "azure-mgmt-reservations==0.2.1",
    "azure-mgmt-resource==23.0.1",
    "azure-mgmt-scheduler==2.0.0",
    "azure-mgmt-search==2.1.0",
    "azure-mgmt-servicebus==0.5.3",
    "azure-mgmt-servicefabric==0.2.0",
    "azure-mgmt-signalr==0.1.1",
    "azure-mgmt-sql==0.9.1",
    "azure-mgmt-storage==21.1.0",
    "azure-mgmt-subscription==0.2.0",
    "azure-mgmt-trafficmanager==0.50.0",
    "azure-mgmt-web==0.35.0",
    "azure-nspkg==3.0.2",
    "azure-storage-blob==12.20.0",
    "blinker==1.6.3",
    "boto3==1.34.30",
    "botocore==1.34.30",
    "certifi==2024.07.04",
    "cffi==1.17.1",
    "charset-normalizer==3.3.1",
    "click==8.1.7",
    "cryptography",
    "dash==2.18.2",
    "dash-bootstrap-components==1.5.0",
    "dash-core-components==2.0.0",
    "dash-cytoscape==0.3.0",
    "dash-html-components==2.0.0",
    "dash-iconify==0.1.2",
    "dash-mantine-components==0.12.1",
    "dash-table==5.0.0",
    "dash_daq==0.5.0",
    "Deprecated==1.2.14",
    "exceptiongroup==1.2.0",
    "Flask==3.0.0",
    "frozenlist==1.4.1",
    "h11==0.14.0",
    "h2==4.1.0",
    "hpack==4.0.0",
    "httpcore==1.0.2",
    "httpx==0.26.0",
    "hyperframe==6.0.1",
    "idna==3.7",
    "importlib-metadata==6.8.0",
    "isodate==0.6.1",
    "itsdangerous==2.1.2",
    "jinja2==3.1.5",
    "jmespath==1.0.1",
    "MarkupSafe==2.1.3",
    "microsoft-kiota-abstractions==1.1.0",
    "microsoft-kiota-authentication-azure==1.0.0",
    "microsoft-kiota-http==1.2.1",
    "microsoft-kiota-serialization-json==1.0.1",
    "microsoft-kiota-serialization-text==1.0.0",
    "msal==1.24.1",
    "msal-extensions==1.1.0",
    "msgraph-core==1.0.0",
    "msgraph-sdk==1.1.0",
    "msrest==0.7.1",
    "msrestazure==0.6.4.post1",
    "multidict==6.0.5",
    "names==0.3.0",
    "nest-asyncio==1.5.8",
    "numpy==1.26.3",
    "oauthlib==3.2.2",
    "opentelemetry-api==1.22.0",
    "opentelemetry-sdk==1.22.0",
    "opentelemetry-semantic-conventions==0.43b0",
    "packaging==23.2",
    "pandas==2.2.3",
    "patsy==0.5.6",
    "pendulum==3.1.0",
    "pip-install==1.3.5",
    "plotly==5.24.1",
    "plotly-express==0.4.1",
    "portalocker==2.8.2",
    "pycparser==2.21",
    "PyJWT==2.8.0",
    "python-dateutil==2.8.2",
    "pytz==2023.3.post1",
    "PyYAML==6.0.1",
    "requests==2.32.4",
    "requests-oauthlib==2.0.0",
    "retrying==1.3.4",
    "s3transfer==0.10.0",
    "scipy==1.10.1",
    "setuptools==72.1.0",
    "six==1.16.0",
    "sniffio==1.3.0",
    "statsmodels==0.14.4",
    "std-uritemplate==0.0.50",
    "tenacity==8.2.3",
    "time-machine==2.13.0",
    "typing_extensions",
    "tzdata==2023.4",
    "urllib3==1.26.19",
    "Werkzeug==3.0.6",
    "wrapt==1.16.0",
    "yarl==1.18.3",
    "zipp==3.19.1",
    "google-auth==2.37.0",
    "pyarrow==18.1.0",
    "hypercorn==0.17.3",
    "gunicorn==23.0.0; platform_system != \"Windows\"",
    "wsproto==1.2.0",
    "asgiref==3.8.1",
    "google-cloud-storage==2.19.0",
    "google-cloud-compute==1.29.0",
    "anthropic==0.62.0",
    "dotenv==0.9.9",
    "tiktoken==0.9.0",
    "pycountry==24.6.1",
    "google-api-python-client==2.118.0",
    "google-cloud-storage-control==1.6.0",
]


[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["attack_techniques*", "core*", "pages*", "agent*"]
exclude = ["local*", "output*", "report*", "assets*", "automator*"]

[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = ["E", "W", "F", "I"]
ignore = ["E501"]  # line too long (handled by formatter)

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"] # unused-import

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"


[dependency-groups]
dev = ["ruff>=0.12.8"]
